import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    dock: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.15,
        shadowRadius: 25,
        elevation: 10,
        borderWidth: 1,
        overflow: 'hidden',
        alignItems: 'center',
    },
    navRow: {
        flexDirection: 'row',
        width: 240, // Fixed width to prevent layout collapse when parent shrinks
        left: '50%',
        marginLeft: -120, // Center it absolutely
        height: 65,
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        position: 'absolute',
        bottom: 0,
    },
    triggerContainer: {
        position: 'absolute',
        bottom: 5,
        left: 0,
        right: 0,
        alignItems: 'center',
        zIndex: 20,
    },
    iconWrapper: {
        width: 60,
        alignItems: 'center',
        justifyContent: 'center'
    },
    iconBtn: {
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    aiTriggerBtn: {
        marginBottom: 2,
    },
    aiGradient: {
        width: 52,
        height: 52,
        borderRadius: 26,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#7C3AED",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 6,
    },
    aiGradientActive: {
        width: 44,
        height: 44,
        borderRadius: 22,
        shadowColor: "transparent",
        opacity: 0.8,
    },
    // Expanded Content
    expandedContent: {
        width: '100%',
        height: '100%',
        paddingBottom: 60,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    aiHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        opacity: 0.6,
        position: 'absolute',
        top: 24,
        width: '100%',
    },
    aiText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
    },
    actionRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'center',
        gap: 20,
        width: '100%',
        paddingBottom: 20,
    },
    actionBtn: {
        alignItems: 'center',
        gap: 8,
        width: 70,
    },
    circleBtn: {
        borderRadius: 99,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    smallBtn: {
        width: 52,
        height: 52,
    },
    largeBtn: {
        width: 72,
        height: 72,
        backgroundColor: '#7C3AED',
        marginBottom: 8,
        shadowColor: "#7C3AED",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
    },
    actionLabel: {
        color: 'white',
        fontSize: 12,
        fontWeight: '500',
        opacity: 0.8,
    },
    waveContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        height: 60,
        paddingBottom: 20,
    },
    waveBar: {
        width: 6,
        borderRadius: 3,
        backgroundColor: '#6366F1',
    }
});
